### ISSUE TITLE
Translated URL ist not stored in translated static page file

### ISSUE THREAD

**Issue by der-On** [wintercms/wn-translate-plugin#91] opened 2024-12-16 10:07 UTC
When setting a translated URL in a static page the url will only be stored in the original static page file as `localeUrl[:locale]` but not in the translated static page file under `url`.

Storing it in the translated static page file is however required for menu items to correctly resolve translated static page URLs.

**Comment by LukeTowers** [comment] 2024-12-19 11:33
@mjauvin seeing a lot of people complain about this after 1.2.7

**Comment by mjauvin** [comment] 2024-12-19 13:50
I've heard of two so far  and I said (on discord) I'd look into it when I get time.

**Comment by mjauvin** [comment] 2024-12-20 18:09
@der-On I cannot reproduce this bug.

It is intended that translated URL be stored in the default language page only, and that does not prevent static pages menu items title/URL from being translated.

The only thing stored in the translated static pages is the translated CONTENT.

Titles and URLs are stored in the DEFAULT language static page under the viewBag as localeTitle[xx] / localeUrl[xx]

**Comment by mjauvin** [comment] 2024-12-20 18:25
Ok, I was able to reproduce the bug (I had previously changed the bindEventOnce() calls to bindEvent()).

So, as stated before on Discord, the following PR broke things in translate plugin:

https://github.com/wintercms/storm/pull/192

So until I issue a fix for Winter.Translate, please revert above PR in your local install and CLEAR CACHE.

**Comment by mjauvin** [comment] 2024-12-20 18:40
@der-On a temporary fix is below for Winter.Translate (without changing Winter Storm):
```diff
diff --git a/behaviors/TranslatablePageUrl.php b/behaviors/TranslatablePageUrl.php
index 11fe845..30341df 100644
--- a/behaviors/TranslatablePageUrl.php
+++ b/behaviors/TranslatablePageUrl.php
@@ -48,7 +48,7 @@ class TranslatablePageUrl extends ExtensionBase
     
         $this->initTranslatableContext();
 
-        $this->model->bindEvent('model.afterFetch', function() {
+        $this->model->bindEventOnce('model.afterFetch', function() {
             $this->translatableDefaultUrl = $this->getModelUrl();
 
             if (!App::runningInBackend()) {
```

**Comment by mjauvin** [comment] 2024-12-20 19:55
Please test with latest dev-main of Winter.Translate and make sure to clear the cache after `composer update`

**Comment by AIC-BV** [comment] 2024-12-28 12:35
@mjauvin 
I did the following on local:
```"winter/wn-translate-plugin": "dev-main",```
```composer update```
```php artisan cache:clear```

But my urls in the menu are still broken.
Where it should go to /quality, it still goes to /kwaliteit (NL main language)
![Image](https://github.com/user-attachments/assets/98b5fd33-5518-4e77-888b-21117b935af6)
![Image](https://github.com/user-attachments/assets/500c400e-eb73-4d5d-bcfb-c5580455cfa5)

This PR however, does 'fix' the pages.
Instead of /en/kwaliteit going to a 404, it now displays the page using /en/kwaliteit, but manually modifying the url to /en/quality now goes to a 404 instead.
@der-On Do you have to same problem?

**Comment by mjauvin** [comment] 2024-12-28 13:15
@AIC-BV I don't understand why this is working for me, that mskes no sense.

**Comment by mjauvin** [comment] 2024-12-28 15:18
@AIC-BV that's a really tricky one with the caching and all... was finally able to reproduce and I commited a change to winter.translate develop branch that should fix the issue.

Make sure you clear the cache after updating with composer.

**Comment by AIC-BV** [comment] 2024-12-28 22:31
Thanks that fixed everything! 🤟

**Comment by mjauvin** [comment] 2024-12-28 23:23
Fixed by https://github.com/wintercms/wn-translate-plugin/commit/f08e3cf1063943aac4c6e87dc040c90160399250

**Closed by mjauvin** 2024-12-28 23:23 UTC
